/* DESCONEXO MVP v6.0.0 - architectural rebuild from reference batches */
(()=>{'use strict';
const VER='6.0.0',CORE='https://cdn.babylonjs.com/babylon.js',GUI='https://cdn.babylonjs.com/gui/babylon.gui.min.js';
const SAVE='desconexo-v6-save',PREF='desconexo-v6-pref';
const K={W:14,D:11,H:3.4,F2:3.4,EYE:1.67,R:.27,WALK:2.35,RUN:5.2,FOCUS:1.25,MOUSE:3000,RANGE:2.45};
const S=read(SAVE,{key:false,bedDoor:false,wardrobe:false,medSeen:false,diary:false,tv:0,distorted:false,done:false});
const P=read(PREF,{sens:1}); function read(k,d){try{return Object.assign({},d,JSON.parse(localStorage.getItem(k)||'{}'))}catch{return Object.assign({},d)}}
const save=()=>localStorage.setItem(SAVE,JSON.stringify(S)),saveP=()=>localStorage.setItem(PREF,JSON.stringify(P));
const load=u=>new Promise((ok,no)=>{let s=document.createElement('script');s.src=u;s.onload=ok;s.onerror=()=>no(new Error('Failed to load '+u));document.head.appendChild(s)});
async function boot(){document.title='DESCONEXO';document.documentElement.style.cssText='width:100%;height:100%;background:#050506';document.body.style.cssText='width:100%;height:100%;margin:0;overflow:hidden;background:#050506';let c=document.createElement('canvas');c.style.cssText='width:100%;height:100%;display:block;outline:0;touch-action:none';c.tabIndex=0;document.body.appendChild(c);try{if(!window.BABYLON)await load(CORE);if(!BABYLON.GUI)await load(GUI);game(c)}catch(e){console.error(e)}}
function game(canvas){const B=BABYLON,G=B.GUI,engine=new B.Engine(canvas,true,{stencil:false,preserveDrawingBuffer:false},true),scene=new B.Scene(engine);engine.setHardwareScalingLevel(Math.max(1,Math.min(1.5,devicePixelRatio||1)));scene.clearColor=new B.Color4(.018,.016,.018,1);scene.skipPointerMovePicking=true;
const cam=new B.UniversalCamera('player',new B.Vector3(10.8,K.F2+K.EYE,8.6),scene);cam.attachControl(canvas,true);cam.inputs.removeByType('FreeCameraKeyboardMoveInput');cam.inertia=0;cam.angularSensibility=K.MOUSE/P.sens;cam.minZ=.04;cam.fov=.8;
const roots={1:new B.TransformNode('first-floor',scene),2:new B.TransformNode('second-floor',scene)};roots[2].position.y=K.F2;
const collision={1:[],2:[]},items=[],V={},input={w:0,a:0,s:0,d:0,run:0,focus:0,up:0,down:0},dev={fly:false};let locked=true,target=null,bob=0,bx=0,by=0,roll=0,subTimer=0;
// Canvas GUI only
const ui=G.AdvancedDynamicTexture.CreateFullscreenUI('gui',true,scene),r=new G.Container();ui.addControl(r);const txt=(v,n=20,c='#eee')=>{let t=new G.TextBlock();t.text=v;t.fontFamily='Arial';t.fontSize=n;t.color=c;t.textWrapping=true;t.isPointerBlocker=false;return t};const box=(bg='#0b0908ed',line='#69564c')=>{let q=new G.Rectangle();q.background=bg;q.color=line;q.thickness=1;q.cornerRadius=2;return q};
let vig=new G.Image('vignette');let svg='<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"><defs><radialGradient id="g" cx="50%" cy="49%" rx="73%" ry="76%"><stop offset="0" stop-color="black" stop-opacity="0"/><stop offset=".78" stop-color="black" stop-opacity="0"/><stop offset=".94" stop-color="black" stop-opacity=".12"/><stop offset="1" stop-color="black" stop-opacity=".30"/></radialGradient></defs><rect width="100%" height="100%" fill="url(#g)"/></svg>';vig.source='data:image/svg+xml,'+encodeURIComponent(svg);vig.width='100%';vig.height='100%';vig.stretch=G.Image.STRETCH_FILL;vig.alpha=.32;vig.isPointerBlocker=false;r.addControl(vig);
let cross=txt('+',28),prompt=txt('',19),objective=txt('',18),status=txt('',16),subtitle=txt('',25),devText=txt('',16,'#ffb24a');cross.width='40px';cross.height='40px';prompt.width='700px';prompt.height='42px';prompt.top='90px';objective.width='600px';objective.height='72px';objective.left='28px';objective.top='35px';objective.horizontalAlignment=G.Control.HORIZONTAL_ALIGNMENT_LEFT;objective.verticalAlignment=G.Control.VERTICAL_ALIGNMENT_TOP;objective.textHorizontalAlignment=G.Control.HORIZONTAL_ALIGNMENT_LEFT;status.width='720px';status.height='35px';status.left='-28px';status.top='25px';status.horizontalAlignment=G.Control.HORIZONTAL_ALIGNMENT_RIGHT;status.verticalAlignment=G.Control.VERTICAL_ALIGNMENT_TOP;status.textHorizontalAlignment=G.Control.HORIZONTAL_ALIGNMENT_RIGHT;subtitle.width='1000px';subtitle.height='85px';subtitle.top='-65px';subtitle.verticalAlignment=G.Control.VERTICAL_ALIGNMENT_BOTTOM;subtitle.alpha=0;devText.width='450px';devText.height='30px';devText.left='-28px';devText.top='56px';devText.horizontalAlignment=G.Control.HORIZONTAL_ALIGNMENT_RIGHT;devText.verticalAlignment=G.Control.VERTICAL_ALIGNMENT_TOP;devText.textHorizontalAlignment=G.Control.HORIZONTAL_ALIGNMENT_RIGHT;[cross,prompt,objective,status,subtitle,devText].forEach(x=>r.addControl(x));
const say=(m,ms=2600)=>{subtitle.text=m;subtitle.alpha=1;clearTimeout(subTimer);subTimer=setTimeout(()=>subtitle.alpha=0,ms)};const btn=(v,fn,alt=0)=>{let b=G.Button.CreateSimpleButton('b'+v,v);b.width='255px';b.height='53px';b.color='#fff';b.background=alt?'#191412':'#7d2029';b.fontSize=18;b.onPointerClickObservable.add(fn);return b};function panel(name,w='800px',h='640px',paper=0){let p=box(paper?'#d4cab1':'#0b0908ed');p.width=w;p.height=h;p.isVisible=false;p.isPointerBlocker=true;r.addControl(p);let st=new G.StackPanel();st.width='88%';p.addControl(st);return[p,st]}function add(st,v,n=21,c='#eee',h=65){let t=txt(v,n,c);t.height=h+'px';st.addControl(t)}function show(p,on){p.isVisible=on;locked=on;if(on)document.exitPointerLock?.();else canvas.requestPointerLock?.()}
let [menu,ms]=panel('menu','830px','680px');menu.isVisible=true;add(ms,'DESCONEXO',54,'#eee',90);add(ms,'ARCHITECTURAL MVP - V'+VER,15,'#b9414c',35);add(ms,'Explore the house and survive the first distortion.',23,'#c8bfb5',95);add(ms,'WASD move | SHIFT run | Q focus | E interact\nP fly mode | SPACE up | CTRL down',18,'#bdb3aa',80);ms.addControl(btn('START GAME',()=>{menu.isVisible=false;locked=false;canvas.focus();canvas.requestPointerLock?.()}));ms.addControl(btn('RESET SAVE',()=>{localStorage.removeItem(SAVE);location.reload()},1));
let [album,as]=panel('album','720px','500px');add(as,'WEDDING ALBUM',17,'#b9414c',46);add(as,'A BLOOD-STAINED PAGE',32,'#eee',68);add(as,'A photograph is marked DEMON. A brass key is attached beside it.',22,'#c8bfb5',125);as.addControl(btn('TAKE KEY',()=>{S.key=true;V.key.forEach(x=>x.isVisible=false);V.keyLight.intensity=0;save();update();show(album,false);say('A brass key. It should open the bedroom door.')}));as.addControl(btn('CLOSE',()=>show(album,false),1));
let [diary,ds]=panel('diary','850px','690px',1);add(ds,'DIARY PAGE',17,'#8c222d',44);add(ds,'12/03/11',32,'#211d18',56);add(ds,'The day was good. We went to the cinema, had dinner and spent the day together. Sometimes he seems so distant.\n\nThe cinema and dinner were excuses to take him to the doctor. The medication was increased. I hope the doctor is right.',21,'#211d18',425);ds.addControl(btn('CLOSE',()=>show(diary,false)));
// Materials and geometry
const mat=(n,c,e)=>{let m=new B.StandardMaterial(n,scene);m.diffuseColor=B.Color3.FromHexString(c);m.specularColor.set(.02,.02,.02);m.backFaceCulling=false;if(e)m.emissiveColor=B.Color3.FromHexString(e);return m};const M={wall:mat('wall','#68645b'),floor:mat('floor','#443530'),wood:mat('wood','#4c2e23'),dark:mat('dark','#11100f'),paper:mat('paper','#c9bd9e'),metal:mat('metal','#9b7530'),bath:mat('bath','#8e9693'),glass:mat('dirty-glass','#4c5554','#080909'),tv:mat('tv','#6f716b','#101410')};M.glass.alpha=.86;
const mesh=(n,x,y,z,w,h,d,m,f=1)=>{let q=B.MeshBuilder.CreateBox(n,{width:w,height:h,depth:d},scene);q.position.set(x,y,z);q.material=m;q.parent=roots[f];return q};const col=(f,n,x,z,w,d)=>collision[f].push({n,minX:x-w/2,maxX:x+w/2,minZ:z-d/2,maxZ:z+d/2});const solid=(n,x,y,z,w,h,d,m,f)=>{let q=mesh(n,x,y,z,w,h,d,m,f);col(f,n,x,z,w,d);return q};const wall=(f,n,x,z,w,d,h=3.18)=>{let q=mesh(n,x,h/2,z,w,h,d,M.wall,f);col(f,n,x,z,w,d);return q};const use=(q,label,fn,enabled=()=>true,range=K.RANGE)=>items.push({q,label,fn,enabled,range});
const hdoor=(f,n,z,x1,x2,c,width=1.0)=>{wall(f,n+'a',(x1+c-width/2)/2,z,c-width/2-x1,.16);wall(f,n+'b',(c+width/2+x2)/2,z,x2-c-width/2,.16)};const vdoor=(f,n,x,z1,z2,c,width=1.0)=>{wall(f,n+'a',x,(z1+c-width/2)/2,.16,c-width/2-z1);wall(f,n+'b',x,(c+width/2+z2)/2,.16,z2-c-width/2)};
function door(f,n,x,z,axis,lockedDoor=0){let d=mesh(n,x,1.25,z,axis==='x'?.12:.94,2.5,axis==='x'?.94:.12,M.wood,f);d.metadata={axis};if(lockedDoor)col(f,n+'-closed',x,z,axis==='x'?.18:1.0,axis==='x'?1.0:.18);return d}function removeCol(f,n){collision[f]=collision[f].filter(x=>x.n!==n)}
function windowObj(f,n,x,z,axis,w=1.2){let frame=mesh(n+'-frame',x,1.65,z,axis==='x'?.16:w,1.55,axis==='x'?w:.16,M.wood,f);let g=mesh(n+'-glass',x+(axis==='x'?-.012:0),1.65,z+(axis==='z'?-.012:0),axis==='x'?.05:w*.82,1.28,axis==='x'?w*.82:.05,M.glass,f);g.isPickable=false;return frame}
// Exterior shell on identical footprint. Walls are continuous because every opening is segmented explicitly.
function shell(f){
 if(f===1){mesh('floor1',7,-.08,5.5,14,.16,11,M.floor,1);mesh('ceiling1-west',3.35,3.22,5.5,6.7,.12,11,M.dark,1);mesh('ceiling1-east',12.45,3.22,5.5,3.1,.12,11,M.dark,1);mesh('ceiling1-center',9.05,3.22,7.05,3.7,.12,7.9,M.dark,1);}
 else{mesh('floor2-west',3.35,-.08,5.5,6.7,.16,11,M.floor,2);mesh('floor2-east',12.45,-.08,5.5,3.1,.16,11,M.floor,2);mesh('floor2-center',9.05,-.08,7.05,3.7,.16,7.9,M.floor,2);mesh('ceiling2',7,3.22,5.5,14,.12,11,M.dark,2);}
 wall(f,'west',0,5.5,.18,11);wall(f,'east',14,5.5,.18,11);wall(f,'north',7,0,14,.18);wall(f,'south',7,11,14,.18)
}
function build(){shell(1);shell(2);
// FIRST FLOOR exact distribution: kitchen NW, corridor below, pantry SW, bathroom S-center, living entire east.
hdoor(1,'kitchen-corridor',4.15,0,7.0,3.8,1.0);hdoor(1,'corridor-services',6.0,0,7.0,3.6,1.0);vdoor(1,'pantry-bath',3.15,6,11,8.0,1.0);vdoor(1,'service-living',7.0,0,11,5.15,1.1);
solid('kitchen-counters',1.1,.48,1.0,2.0,.96,.65,M.wood,1);solid('pantry-shelf',.55,1.1,8.3,.62,2.2,3.4,M.wood,1);solid('bath1-sink',4.8,.5,9.8,1.2,1,.58,M.bath,1);solid('living-sofa',10.5,.55,7.6,2.6,1.1,1,M.wood,1);
// Main door on east living wall, permanently locked.
let main=door(1,'main-door',14,6.15,'x',1);use(main,'[E] TRY MAIN DOOR',()=>say('It will not open.'));
// TV faces inward from south wall.
solid('tv-cabinet',10.6,.55,10.45,2.5,1.1,.62,M.dark,1);let tv=mesh('tv-screen',10.6,1.42,10.12,2.25,1.48,.04,M.tv,1);V.tv=tv;
// Windows first floor: kitchen north, corridor west/rear, bathroom south, living east/south. Dirty glass is opaque.
windowObj(1,'kitchen-window',2.0,0,'z',1.15);windowObj(1,'corridor-window',0,5.1,'x',1.1);windowObj(1,'bath1-window',4.8,11,'z',.75);windowObj(1,'living-window-east',14,8.35,'x',1.5);windowObj(1,'living-window-north',11.7,0,'z',1.2);
// SECOND FLOOR distribution: parents NW, Sala 2 NE/center, closet SW, bath S-center, protagonist SE.
vdoor(2,'parents-sala',4.7,0,4.9,3.55,1.0);hdoor(2,'upper-lower',5.7,0,14,10.5,1.05);vdoor(2,'closet-bath',2.35,5.7,11,7.7,1.0);vdoor(2,'bath-protag',6.6,5.7,11,8.1,1.0);
solid('parents-bed',2.3,.48,2.2,2.5,.96,3.1,M.wood,2);let closet=solid('parents-closet',.7,1.25,8.25,.72,2.5,3.0,M.wood,2);solid('bath2-sink',4.45,.5,9.75,1.25,1,.58,M.bath,2);solid('protagonist-bed',10.4,.48,8.5,2.7,.96,3.2,M.wood,2);solid('sala2-sofa',7.2,.55,2.4,2.35,1.1,1,M.wood,2);
// Correct doors: closed leaves parallel to containing wall.
let parent=door(2,'parents-door',4.7,3.55,'x',1);use(parent,'[E] PARENTS ROOM IS LOCKED',()=>say('This door will not open.'));
let bathDoor=door(2,'bath2-door',5.0,5.7,'z',0);bathDoor.rotation.y=Math.PI/2;bathDoor.position.x=4.53;
let bedDoor=door(2,'protagonist-door',10.5,5.7,'z',!S.bedDoor);if(S.bedDoor){bedDoor.isVisible=false}else use(bedDoor,()=>S.key?'[E] UNLOCK BEDROOM DOOR':'THE DOOR IS LOCKED',()=>{if(!S.key)return say('Locked. Find the key.');S.bedDoor=true;bedDoor.isVisible=false;removeCol(2,'protagonist-door-closed');save();update();say('The bedroom door unlocks.')},()=>!S.bedDoor);if(!S.bedDoor)col(2,'protagonist-door-closed',10.5,5.7,1.05,.18);
// Parent closet-only connection remains inside locked parents room.
let closetDoor=door(2,'closet-door',2.35,7.7,'x',1);
// Windows second floor: parents rear, bath south/front, protagonist south/front, Sala 2 east/front.
windowObj(2,'parents-window',2.0,0,'z',1.15);windowObj(2,'bath2-window',4.5,11,'z',.72);windowObj(2,'protagonist-window',10.3,11,'z',1.65);windowObj(2,'sala2-window',14,3.4,'x',.9);
// Protagonist wardrobe, album/key, medication, diary geometry.
let wardrobe=solid('marked-wardrobe',13.25,1.3,8.4,.72,2.6,2.3,M.wood,2);use(wardrobe,'[E] INSPECT WARDROBE',()=>{S.wardrobe=true;save();update();say('Deep scratch marks cover the wood.',3000)});
let album=mesh('album',10.4,1.02,8.0,.78,.08,.96,M.dark,2);let keyStem=mesh('key-stem',10.4,1.13,8,.1,.04,.45,M.metal,2),keyRing=B.MeshBuilder.CreateTorus('key-ring',{diameter:.24,thickness:.05,tessellation:16},scene);keyRing.position.set(10.4,1.17,8.2);keyRing.parent=roots[2];keyRing.material=M.metal;let kl=new B.PointLight('key-light',new B.Vector3(10.4,1.65,8),scene);kl.parent=roots[2];kl.diffuse.set(.85,.45,.12);kl.range=3;kl.intensity=S.key?0:1;V.key=[keyStem,keyRing];V.keyLight=kl;V.key.forEach(x=>x.isVisible=!S.key);use(album,'[E] INSPECT ALBUM',()=>show(albumPanel,true),()=>!S.key);
let med=mesh('medication-bottle',4.45,1.13,9.55,.18,.42,.18,M.metal,2);use(med,()=>S.distorted?'[E] TAKE MEDICATION':'[E] INSPECT MEDICATION',()=>{if(S.distorted){S.distorted=false;S.done=true;apply();say('The house becomes still again.',3300)}else{S.medSeen=true;save();update();say('Medication. The label says twice a day.')}},()=>!S.done);
let db=mesh('diary-book',7.2,.82,2.45,.72,.1,.52,M.wood,2),dp=mesh('diary-page',7.2,.89,2.45,.64,.025,.44,M.paper,2);db.rotation.y=dp.rotation.y=.15;use(dp,'[E] READ DIARY PAGE',()=>{S.diary=true;save();update();show(diaryPanel,true)});
createStairs();}
// GUI aliases after geometry callback definitions
const albumPanel=album,diaryPanel=diary;
// Switchback stairs matching references: lower flight east to west, landing, upper flight west to east.
const stair={xL:8.0,xR:12.15,zLower:2.45,zUpper:.95,w:1.12,landingX:7.45,mid:K.F2/2};
function createStairs(){let n=11,run=stair.xR-stair.xL,sw=run/n;for(let i=0;i<n;i++){let h=(i+1)*stair.mid/n;mesh('lower-step-'+i,stair.xR-sw*(i+.5),h/2,stair.zLower,sw+.025,h,stair.w,M.wood,1)}mesh('middle-landing',stair.landingX,stair.mid-.06,1.7,1.35,.12,2.3,M.wood,1);for(let i=0;i<n;i++){let h=stair.mid+(i+1)*stair.mid/n;mesh('upper-step-'+i,stair.xL+sw*(i+.5),h/2,stair.zUpper,sw+.025,h,stair.w,M.wood,1)} }
function stairY(x,z){if(z>1.88&&z<3.02&&x>=stair.xL&&x<=stair.xR)return (stair.xR-x)/(stair.xR-stair.xL)*stair.mid;if(x>6.78&&x<8.12&&z>.52&&z<3.0)return stair.mid;if(z>.38&&z<1.52&&x>=stair.xL&&x<=stair.xR)return stair.mid+(x-stair.xL)/(stair.xR-stair.xL)*stair.mid;return null}
build();
// Open stairwell replaces floor/ceiling in stair zone by overlaying floor pieces; hide original second floor slab locally via architecture layout pieces not collider.
const amb=new B.HemisphericLight('ambient',new B.Vector3(0,1,0),scene);amb.diffuse.set(.8,.77,.69);amb.groundColor.set(.11,.09,.09);amb.intensity=.61;let lamp=new B.PointLight('player-light',B.Vector3.Zero(),scene);lamp.parent=cam;lamp.diffuse.set(.7,.63,.53);lamp.range=5.2;lamp.intensity=.22;let red=new B.PointLight('red',new B.Vector3(10,2,8),scene);red.diffuse.set(.8,.01,.01);red.range=16;red.intensity=0;
function apply(){amb.intensity=S.distorted?.14:.61;red.intensity=S.distorted?1.9:0;vig.alpha=S.distorted?.46:.32;M.tv.emissiveColor=S.distorted?new B.Color3(.55,.01,.01):new B.Color3(.08,.1,.08);save();update()}
function floorNow(){return cam.position.y>K.EYE+K.F2*.5?2:1}function hit(x,z,f=floorNow()){for(let a of collision[f]){let nx=Math.max(a.minX,Math.min(x,a.maxX)),nz=Math.max(a.minZ,Math.min(z,a.maxZ)),dx=x-nx,dz=z-nz;if(dx*dx+dz*dz<K.R*K.R)return true}return false}
function move(dx,dz){let p=cam.position,sy=stairY(p.x+dx,p.z+dz),f=sy===null?floorNow():(sy>K.F2*.5?2:1);if(!hit(p.x+dx,p.z,f))p.x+=dx;if(!hit(p.x,p.z+dz,f))p.z+=dz;sy=stairY(p.x,p.z);p.y=K.EYE+(sy===null?(floorNow()===2?K.F2:0):sy)}
function update(){let f=floorNow();status.text=`FLOOR ${f} | KEY ${S.key?'YES':'NO'} | DIARY ${S.diary?'YES':'NO'} | MEDICATION ${S.medSeen?'SEEN':'NO'}`;objective.text=!S.wardrobe?'Inspect the wardrobe in the protagonist bedroom.':!S.key?'Inspect the wedding album.':!S.bedDoor?'Unlock the bedroom door.':!S.medSeen?'Inspect the medication in Bathroom 2.':!S.diary?'Read the diary page in Sala 2.':S.tv===0?'Walk downstairs into the living room.':S.distorted?'Escape upstairs and take the medication.':'MVP complete.'}
function key(c,v){if(c==='KeyW')input.w=v;if(c==='KeyA')input.a=v;if(c==='KeyS')input.s=v;if(c==='KeyD')input.d=v;if(c==='ShiftLeft'||c==='ShiftRight')input.run=v;if(c==='KeyQ')input.focus=v;if(c==='Space')input.up=v;if(c==='ControlLeft'||c==='ControlRight')input.down=v}
function toggle(){dev.fly=!dev.fly;devText.text=dev.fly?'DEVELOPMENT MODE: FLY / NOCLIP':'';say(dev.fly?'Fly mode enabled.':'Walk mode enabled.',1300);if(!dev.fly){let f=floorNow();cam.position.y=K.EYE+(f===2?K.F2:0);if(hit(cam.position.x,cam.position.z,f))cam.position.set(10.8,K.F2+K.EYE,8.6)}}
window.addEventListener('keydown',e=>{if(e.code==='KeyP'&&!e.repeat)return toggle();key(e.code,1);if(e.code==='KeyE'&&target&&!locked)target.fn();if(e.code==='Minus'){P.sens=Math.max(.25,P.sens-.05);cam.angularSensibility=K.MOUSE/P.sens;saveP()}if(e.code==='Equal'){P.sens=Math.min(2,P.sens+.05);cam.angularSensibility=K.MOUSE/P.sens;saveP()}});window.addEventListener('keyup',e=>key(e.code,0));window.addEventListener('blur',()=>Object.keys(input).forEach(k=>input[k]=0));canvas.addEventListener('click',()=>{if(!locked&&!document.pointerLockElement)canvas.requestPointerLock?.()});
scene.onBeforeRenderObservable.add(()=>{let dt=Math.min(engine.getDeltaTime()/1000,.04);cam.position.y-=by;cam.position.x-=bx;by=bx=0;if(locked){prompt.text='';return}let fw=input.w-input.s,sd=input.d-input.a,l=Math.hypot(fw,sd);if(l){fw/=l;sd/=l}let run=input.run&&l&&!input.focus&&!input.s,sp=dev.fly?(input.run?14:8):(input.focus?K.FOCUS:(run?K.RUN:K.WALK)),yaw=cam.rotation.y,pitch=cam.rotation.x,fx=Math.sin(yaw),fz=Math.cos(yaw),rx=Math.cos(yaw),rz=-Math.sin(yaw);if(dev.fly){cam.position.x+=(Math.sin(yaw)*Math.cos(pitch)*fw+rx*sd)*sp*dt;cam.position.z+=(Math.cos(yaw)*Math.cos(pitch)*fw+rz*sd)*sp*dt;cam.position.y+=(-Math.sin(pitch)*fw+(input.up-input.down))*sp*dt}else move((fx*fw+rx*sd)*sp*dt,(fz*fw+rz*sd)*sp*dt);let tf=input.focus?.58:(run?.89:.8);cam.fov+=(tf-cam.fov)*Math.min(1,dt*12);if(l&&!dev.fly){bob+=dt*(run?13.5:8.3);by=Math.sin(bob*2)*(run?.032:.018);bx=Math.cos(bob)*(run?.01:.006);cam.position.y+=by;cam.position.x+=bx}roll+=(((input.d-input.a)*(run?-.012:-.006))-roll)*Math.min(1,dt*12);cam.rotation.z=roll+(S.distorted?Math.sin(performance.now()/170)*.003:0);
// Automatic TV escalation on entering the living room after required upstairs clues.
if(!dev.fly&&floorNow()===1&&S.medSeen&&S.diary&&S.tv===0&&cam.position.x>7.2&&cam.position.z>3.5){S.tv=1;save();V.tv.material.emissiveColor=new B.Color3(.22,.22,.2);say('The television turns on by itself.',2500);setTimeout(()=>{if(S.tv===1){S.tv=2;V.tv.material.emissiveColor=new B.Color3(.35,.12,.09);say('The person on screen moves faster.',2800)}},3200);setTimeout(()=>{if(S.tv===2){S.tv=3;S.distorted=true;apply();say('TAKE THE MEDICATION.',4200)}},6800)}
let ray=cam.getForwardRay(K.RANGE),best=null,bd=99;for(let i of items){if(!i.enabled()||!i.q.isEnabled())continue;let h=ray.intersectsMesh(i.q,false);if(h.hit&&h.distance<i.range&&h.distance<bd){best=i;bd=h.distance}}target=best;prompt.text=best?(typeof best.label==='function'?best.label():best.label):'';cross.scaleX=cross.scaleY=input.focus?.75:1;update()});
apply();update();engine.runRenderLoop(()=>scene.render());window.addEventListener('resize',()=>engine.resize());window.DESCONEXO={version:VER,scene,engine,camera:cam,state:S,collision,development:dev};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();})();
